### ISSUE TITLE
Any chance to fix the dead web server?

### ISSUE THREAD

**Issue by strexy** [leafo/sightreading.training#31] opened 2018-05-19 07:20 UTC
https://sightreading.training is unreachable, error 502.
Thanks.

**Comment by aik099** [comment] 2018-05-19 18:30
Duplicate of #30.

**Comment by leafo** [comment] 2018-05-19 19:38
Sorry about that, site is back now.

**Closed by leafo** 2018-05-19 19:38 UTC

**Comment by strexy** [comment] 2018-05-19 20:08
Thanks for fixing it.
