### ISSUE TITLE
Flats not recognized

### ISSUE THREAD

**Issue by soundscape009** [leafo/sightreading.training#61] opened 2019-10-02 04:12 UTC
Setup
Browser: Chrome
Connection: MIDI
Piano: Yamaha P-125

Issue: B flat and E flat are not recognized when playing in F major or Bb major chord practice.  B flat and E flat either get recognized as A sharp or F but not flat. Therefore i am unable to progress on the F and B flat chord practice sections.

**Comment by almagestalpha** [comment] 2019-10-02 06:57
I have the same issue since a long time now. It's independent from the midi-device, if i use the keyboard from the website, the problem is still there: no flats are recognized. 
Maybe the OS is the source of the problem? I work on Mac OSX 10.11.
Or the Yamaha-midi-driver somehow makes problems, i use a yamaha p-250.
Since many people seem to have the same problem here, i guess it could be helpful, to find out what they have in common.

**Comment by leafo** [comment] 2019-12-22 02:41
Closing this, duplicate of #70 (which has been fixed)

**Closed by leafo** 2019-12-22 02:41 UTC
